%Set preferences with setdbprefs.
setdbprefs('DataReturnFormat', 'numeric');
setdbprefs('NullNumberRead', 'NaN');
setdbprefs('NullStringRead', 'null');
setdbprefs('FetchBatchSize', '10000');

%Make connection to database.  Note that the password has been omitted.
%Using JDBC driver.
conn = database('energydata', 'student', 'bassconnex', 'Vendor', 'MYSQL', 'Server', '67.159.81.86', 'PortNumber', 3306);

%Read data from database.
curs = exec(conn, ['SELECT 	smart_home.timestamp'...
    ' ,	smart_home.b7139_03_r_01_refrig'...
    ' ,	smart_home.b7139_04_r_06_hotbox'...
    ' ,	smart_home.b7139_05_r_01_ahu1'...
    ' ,	smart_home.b7139_05_r_03_ahu2'...
    ' ,	smart_home.b7139_05_r_05_cu1'...
    ' ,	smart_home.b7139_05_r_07_cu2'...
    ' ,	smart_home.b7139_05_r_09_airrecunit'...
    ' ,	smart_home.b7139_06_r_02_erv'...
    ' ,	smart_home.b7139_06_r_03_h10p'...
    ' FROM 	energydata.smart_home '...
    ' WHERE 	smart_home.timestamp <= 1425186000'...
    ' AND 	smart_home.timestamp >= 1422766800']);

curs = fetch(curs);
close(curs);

%Assign data to output variable
fetchedData = curs.Data;

%Close database connection.
close(conn);

%Clear variables
clear curs conn